#!/bin/bash
COOKIES_FILE='cookies.txt'
TIMESTAMP=$(date +'%Y-%m-%d-%H:%M:%S')

while read username; do #collects scraps and galleries in separate directories under the same parent
	mkdir ./snapshot-$TIMESTAMP
	cd    ./snapshot-$TIMESTAMP

	mkdir ./$username
	cd    ./$username

	mkdir ./gallery
	cd    ./gallery
	
	sh ../../../furaffinity-dl.sh gallery/$username ../../../$COOKIES_FILE
	
	cd    ..
	mkdir ./scraps
	cd    ./scraps
	
	sh ../../../furaffinity-dl.sh scraps/$username ../../../$COOKIES_FILE
	
	cd ../../..
done <usernames.txt
