#!/bin/bash
COOKIES_FILE='cookies.txt'
TIMESTAMP=$(date +'%Y-%m-%d-%H:%M:%S')

mkdir ./snapshot-$TIMESTAMP

while read username; do #collects scraps and galleries in separate directories under the same parent
	cd    ./snapshot-$TIMESTAMP

	mkdir ./$username
	cd    ./$username

	mkdir ./gallery
	cd    ./gallery
	
	../../../furaffinity-dl gallery/$username ../../../$COOKIES_FILE
	
	cd    ..
	mkdir ./scraps
	cd    ./scraps
	
	../../../furaffinity-dl scraps/$username ../../../$COOKIES_FILE
	
	cd ../../..
done <usernames.txt
